Mail setup fixes
- Improved safety of bash script
- Improved safety of python script
- Added better notifications of fail
- Improved markdown formatting: now line breaks are hard, and configured
  vim to use soft lines

diff --git a/bin/bin/util/mutt-sendmail-markdown-wrapper b/bin/bin/util/mutt-sendmail-markdown-wrapper
--- a/bin/bin/util/mutt-sendmail-markdown-wrapper
+++ b/bin/bin/util/mutt-sendmail-markdown-wrapper
@@ -1,8 +1,17 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+set -Eeuo pipefail
+trap cleanup SIGINT SIGTERM ERR
+
+cleanup() {
+  trap - SIGINT SIGTERM ERR
+  # script cleanup here
+  notify-send "MAIL SEND FAILED"
+}
 
 tmpfile="$(mktemp --tmpdir mailmessage.XXXX)"
 
-# mutt will pipe email text into stdin
+# mutt will pipe email text into 
 ~/bin/modules/add-html-to-email > "$tmpfile"
 
 {
@@ -12,6 +21,8 @@ tmpfile="$(mktemp --tmpdir mailmessage.XXXX)"
 
     if [[ -f "$tmpfile" ]]; then
       < "$tmpfile" sendmail "$@"
+    else
+      cleanup
     fi
 
     rm "$tmpfile"
